name: Docker Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker compose stack
      run: cd docker && ./build.sh
    - name: Run docker-compose
      run: cd docker && docker-compose up -d
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Check running containers
      run: docker ps -a
    - name: Check if container blackboard_fastapi is alive
      run: cd docker && docker-compose exec -T blackboard_fastapi echo "I am up"
    - name: Get Failed FastAPI logs
      if: ${{ failure() }}
      run: cd docker && docker-compose logs blackboard_fastapi
    - name: Check if container blackboard_reverse_proxy is alive
      run: cd docker && docker-compose exec -T blackboard_reverse_proxy echo "I am up"
    - name: Get Failed Nginx logs
      if: ${{ failure() }}
      run: cd docker && docker-compose logs blackboard_reverse_proxy
